[podcasts]
"知行小酒馆" = "https://feed.xyzfm.space/j8yp8gxkmgqr"
"中场沉思录" = "https://feed.xyzfm.space/jtvfkcxqmnkg"
"无人知晓" = "https://feed.xyzfm.space/ypn9dydpbxpc"
"面基" = "https://feed.xyzfm.space/6hpdgggtxpxb"
"MacTalk·夜航西飞" = "https://feed.xyzfm.space/9mkbwqtmr8ma"
"三五环" = "https://feed.xyzfm.space/m3dda867gh7j"
"长话长说" = "https://feed.xyzfm.space/blgurjvuy6bq"
"全职业绿洲" = "https://feed.xyzfm.space/38qmt4tuh4jh"
"奇想驿" = "https://feed.xyzfm.space/4wq8y3ymmc7p"
"设计杂谈" = "https://anyway.fm/rss.xml"
