from typing import Final

DOUBAO_MODEL_NAME: Final = "doubao-ime-asr"
DOUBAO_PROTOCOL_VERSION: Final = "apk-1.3.17-twopass"
DOUBAO_RESPONSE_MAX_ATTEMPTS: Final = 3
DOUBAO_RETRY_BASE_DELAY_SECONDS: Final = 1.0
DOUBAO_MISSING_FINAL_SEGMENT_THRESHOLD: Final = 5
DEFAULT_DOUBAO_MAX_IN_FLIGHT_REQUESTS: Final = 30
DEFAULT_DOUBAO_REQUEST_INTERVAL_SECONDS: Final = 1.0
